### ISSUE TITLE
On fs 1.6.10 seem to get one way audio

### ISSUE THREAD

**Issue by blackc2004** [xadhoom/mod_bcg729#12]
On FS 1.6.10, I'm getting 1 way audio when one side of the call is in PCMU and the other is in G729. If i put both sides of call into g729 or both sides in PCMI all works fine. But for some reason transcoding is not working. I wasn't noticing this issue on fs1.6.9

**Comment by p00h** [comment]
I can confirm the issue. I had the same problem unless I turned off PCMU/PCMA support. Fortunately I was able to do it.

**Comment by joelsdc** [comment]
Hi guys, any update on this? Have you been able to reproduce the one-way-audio on latest 1.6.14? Have you seen anything in the changelog from 1.6.9 to 1.6.10 that could cause this?

**Comment by joelsdc** [comment]
Update: I tested this yesterday on fs 1.6.14 and I was able to transcode G729 to G711.

**Comment by xadhoom** [comment]
Right now I know for sure that is been used with latest v1.6 branch without issues, and unfortunately I don't have time to do debug on older versions/systems.

A quick glance to FS codec APIs does not show any breaking change.
