### ISSUE TITLE
G729 Royality Free since 1st of January 2017

### ISSUE THREAD

**Issue by MartB** [xadhoom/mod_bcg729#20]
Source:
http://www.sipro.com/G729.html

The way the official statement is phrased makes me believe you can safely get rid of the paragraph describing the royality fees in the readme.

Good news for everyone
Kind regards
MartB

**Comment by xadhoom** [comment]
seems that also wikipedia confirms that:

https://en.wikipedia.org/wiki/G.729

As soon as I've some time to read it better, I'll remove it.
