### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mtrr** [xadhoom/mod_bcg729#6]
with the recent changes in libbcg729 the following problem pops up:

mod_bcg729.c: In function ‘switch_bcg729_init’:
mod_bcg729.c:61:39: error: too few arguments to function ‘initBcg729EncoderChannel’
             context->encoder_object = initBcg729EncoderChannel();

(and a few more)

cheers

**Comment by xadhoom** [comment]
seems that they're introducing support for Annex B (which is interesting), so APIs changed a bit.

Unfortunately right now I've no time into checking out the changes and include them, 
I've just pushed a little fix in the makefile that checks out a specific version that should work.
